version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2023-12-14T18-51-57Z
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./volumes/minio:/data
    command: server --address 0.0.0.0:9000 /data --console-address 0.0.0.0:9090
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      default:
